
db.path=./data/daily_logs.db


# --- CSLSM folder configuration ---
cslsm.dir.unprocessed = ./CSLSM/incoming
cslsm.dir.processed   = ./CSLSM/processed
cslsm.dir.failed      = ./CSLSM/failed

# (optional) accepted Excel extensions, comma-separated
cslsm.excel.exts = .xlsx,.xlsm,.xls
